services:
  prizm-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    volumes:
      - ./templates:/app/templates
    restart: unless-stopped