name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Copy static files
        run: |
          mkdir -p _site
          cp -r templates/* _site/
          # Use the static version of index.html
          if [ -f _site/index.html.static ]; then
            mv _site/index.html.static _site/index.html
          fi
          
          # Create a simple API documentation page
          cat > _site/api-docs.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>PRIZM API Documentation</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      line-height: 1.6;
                  }
                  h1, h2, h3 {
                      color: #333;
                  }
                  pre {
                      background-color: #f5f5f5;
                      padding: 10px;
                      border-radius: 5px;
                      overflow-x: auto;
                  }
                  code {
                      font-family: monospace;
                  }
              </style>
          </head>
          <body>
              <h1>PRIZM API Documentation</h1>
              <p>This documentation describes how to use the PRIZM Code Lookup API.</p>
              
              <h2>API Endpoints</h2>
              
              <h3>Single Postal Code Lookup</h3>
              <pre><code>GET /api/prizm?postal_code=V8A2P4</code></pre>
              <p>Response:</p>
              <pre><code>{
                "postal_code": "V8A 2P4",
                "prizm_code": "62",
                "status": "success"
              }</code></pre>
              
              <h3>Batch Postal Code Lookup</h3>
              <pre><code>POST /api/prizm/batch
          Content-Type: application/json
          
          {
            "postal_codes": ["V8A2P4", "M5V2H1", "K1A0A9"]
          }</code></pre>
              <p>Response:</p>
              <pre><code>{
                "results": [
                  {
                    "postal_code": "V8A 2P4",
                    "prizm_code": "62",
                    "status": "success"
                  },
                  {
                    "postal_code": "M5V 2H1",
                    "prizm_code": "01",
                    "status": "success"
                  },
                  {
                    "postal_code": "K1A 0A9",
                    "prizm_code": "11",
                    "status": "success"
                  }
                ],
                "total": 3,
                "successful": 3
              }</code></pre>
              
              <p><a href="index.html">Back to Home</a></p>
          </body>
          </html>
          EOL
          
          # Create a simple README page
          cat > _site/readme.html << 'EOL'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>PRIZM Code Lookup - About</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 20px;
                      line-height: 1.6;
                  }
                  h1, h2, h3 {
                      color: #333;
                  }
                  pre {
                      background-color: #f5f5f5;
                      padding: 10px;
                      border-radius: 5px;
                      overflow-x: auto;
                  }
                  code {
                      font-family: monospace;
                  }
              </style>
          </head>
          <body>
              <h1>PRIZM Code Lookup API</h1>
              <p>This tool provides an API endpoint for users to submit Canadian postal codes and retrieve the associated PRIZM codes from Environics Analytics.</p>
              
              <h2>Features</h2>
              <ul>
                  <li>Single postal code lookup via GET request</li>
                  <li>Batch postal code lookup via POST request</li>
                  <li>Web interface for easy testing</li>
                  <li>Parallel processing for batch requests</li>
              </ul>
              
              <h2>How It Works</h2>
              <ol>
                  <li>The API receives a postal code request</li>
                  <li>It uses Selenium to navigate to the PRIZM website</li>
                  <li>It enters the postal code in the search field</li>
                  <li>It extracts the PRIZM code from the search results</li>
                  <li>It returns the result to the user</li>
              </ol>
              
              <p><a href="index.html">Back to Home</a> | <a href="api-docs.html">API Documentation</a></p>
          </body>
          </html>
          EOL
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2